### ISSUE TITLE
query with orderby #question

### ISSUE THREAD

**Issue by inv2004** [appsignal/mongo-rust-driver#46]
Hello,

Could you please show and example how to use find with orderby?
I found in c-mongo that its necessary to put query in something like this:
```
.find{doc!{"$query":{"type": "record"}, "$orderby":{"index":1}})
```
but it panics with the following error:
```
"errmsg" : "unknown top level operator: $query",
```
mongodb 4.0.2

Thank you,

**Comment by gngeorgiev** [comment]
@inv2004 nice bro, I guess you found a solution. So good of you to share it with us mortals :)

**Comment by inv2004** [comment]
@gngeorgiev 

Please use it, bro:
```
let query = doc!{
            "$query": { "type": "ticker" },
            "$orderby": {"sequence": 1}
        };

let cursor = self.coll.find(&query, Some(&opt)).unwrap();
```

I am not so sure what was wrong, but this one works.

**Comment by gngeorgiev** [comment]
@inv2004 Thanks, that's it.

The query doesn't work if there's only an `$orderby` key, it needs a `$query` key too, then it works!

I guess this is some logic in bsonc/mongoc but since the `mongoc_collection_find` function will most likely be deprecated in favor of `mongoc_collection_find_with_opts` that uses the new query syntax (http://mongoc.org/libmongoc/current/mongoc_collection_find.html#the-find-command) this issue wouldn't matter for much longer.
